### ISSUE TITLE
Jumping between files destroys jump history

### ISSUE THREAD

**Issue by blkgoose** [danielefongo/microscope#1]
While jumping between pieces of the same file, the history is not updated and it's impossible to <C-O> <C-I> to move back and forth.

How to reproduce:
* open a file
* open a second file
* search for something in the current file
* follow the result
* <C-O>

**Comment by danielefongo** [comment]
Fixed in https://github.com/danielefongo/microscope-files/commit/19cd04838754940782177083843facf6950e004c
