### ISSUE TITLE
Add CI regression tests

### ISSUE THREAD

**Issue by blkgoose** [danielefongo/microscope#6]
https://github.com/junegunn/vader.vim

**Comment by danielefongo** [comment]
I will add the tests, it was something I already wanted to do. However, I will use the [test harness from Plenary](https://github.com/nvim-lua/plenary.nvim#plenarytest_harness).

**Comment by danielefongo** [comment]
Started to add some tests (see [here](https://github.com/danielefongo/microscope/commit/904fbe469758f3d7ebd2b0f9c55fa1729f763db3)). 

It could be nice to create a Github action

**Comment by danielefongo** [comment]
Added CI (first :green_circle:  github action running [here](https://github.com/danielefongo/microscope/actions/runs/5202219733) :muscle: )
